//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sketch360.XPlat.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sketch360.XPlat.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Sketch 360....
        /// </summary>
        public static string AboutMenuItem {
            get {
                return ResourceManager.GetString("AboutMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Sketch 360.
        /// </summary>
        public static string AboutSketch360 {
            get {
                return ResourceManager.GetString("AboutSketch360", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a Microsoft Garage Project.
        /// </summary>
        public static string AMicrosoftGarageProject {
            get {
                return ResourceManager.GetString("AMicrosoftGarageProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sketch 360 helps you easily create 360 degree panoramic sketches, which are useful when you want to create a quick sketch of a space, real or virtual when modeling may take too long. 
        ///Whether you are an architect, a VR designer, an urban sketcher, a 3D game designer or a 360 video producer, you can easily construct an accurate sketch from a single viewpoint that&apos;s easily shareable online using Sketch 360..
        /// </summary>
        public static string CarouselAppText {
            get {
                return ResourceManager.GetString("CarouselAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw on one pane using equirectangular grid and stencils as guides.  The stencils help you draw the vertical and curved horizontal lines that end up looking straight when seen in 360..
        /// </summary>
        public static string CarouselDrawingText {
            get {
                return ResourceManager.GetString("CarouselDrawingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export these images as viewable as 360 degree photos on sites like Facebook.com, Adobe Lightroom, Kuula.co or apps like VR Media Player..
        /// </summary>
        public static string CarouselExportText {
            get {
                return ResourceManager.GetString("CarouselExportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKIP.
        /// </summary>
        public static string CarouselSkip {
            get {
                return ResourceManager.GetString("CarouselSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As you draw, the flat sketch is projected to the inside of a sphere with you at the center.  You can activate the motion sensors on your device to use the tilt and rotation of the device to determine the gaze orientation..
        /// </summary>
        public static string CarouselSphericalText {
            get {
                return ResourceManager.GetString("CarouselSphericalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s Start.
        /// </summary>
        public static string CarouselStart {
            get {
                return ResourceManager.GetString("CarouselStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen color.
        /// </summary>
        public static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by 
        ///Michael S. Scherotter
        ///Matthew Leibowitz
        ///Shane Neuville
        ///Komal Priya
        ///Jon Martin.
        /// </summary>
        public static string CreatedByMichaelScherotter {
            get {
                return ResourceManager.GetString("CreatedByMichaelScherotter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1}-{2:00}-{3:00} {4:00}.{5:00}.{6:00}.{7}.
        /// </summary>
        public static string DateFilenameFormat {
            get {
                return ResourceManager.GetString("DateFilenameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing color.
        /// </summary>
        public static string DrawingColor {
            get {
                return ResourceManager.GetString("DrawingColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export image.
        /// </summary>
        public static string ExportImage {
            get {
                return ResourceManager.GetString("ExportImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export resolution.
        /// </summary>
        public static string ExportResolutions {
            get {
                return ResourceManager.GetString("ExportResolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equirectangular tools (Eq A Snap) by António Bandeira Araújo..
        /// </summary>
        public static string GridBy {
            get {
                return ResourceManager.GetString("GridBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid opacity.
        /// </summary>
        public static string GridOpacity {
            get {
                return ResourceManager.GetString("GridOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help....
        /// </summary>
        public static string HelpMenuItem {
            get {
                return ResourceManager.GetString("HelpMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lanscape drawing pane.
        /// </summary>
        public static string LandscapeDrawingScreen {
            get {
                return ResourceManager.GetString("LandscapeDrawingScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load initial sketch.
        /// </summary>
        public static string LoadInitialSketch {
            get {
                return ResourceManager.GetString("LoadInitialSketch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading the initial sketch will replace the current sketch.  Press OK to continue..
        /// </summary>
        public static string LoadInitialSketchMessage {
            get {
                return ResourceManager.GetString("LoadInitialSketchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New sketch.
        /// </summary>
        public static string NewSketch {
            get {
                return ResourceManager.GetString("NewSketch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open sketch....
        /// </summary>
        public static string OpenSketch {
            get {
                return ResourceManager.GetString("OpenSketch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen size.
        /// </summary>
        public static string PenSize {
            get {
                return ResourceManager.GetString("PenSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait drawing pane.
        /// </summary>
        public static string PortraitDrawingScreen {
            get {
                return ResourceManager.GetString("PortraitDrawingScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy &amp; Cookies.
        /// </summary>
        public static string PrivacyAndCookies {
            get {
                return ResourceManager.GetString("PrivacyAndCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save sketch....
        /// </summary>
        public static string SaveSketch {
            get {
                return ResourceManager.GetString("SaveSketch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        public static string SettingsMenuItem {
            get {
                return ResourceManager.GetString("SettingsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share....
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show introduction.
        /// </summary>
        public static string ShowIntroduction {
            get {
                return ResourceManager.GetString("ShowIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sketch 360.
        /// </summary>
        public static string Sketch360 {
            get {
                return ResourceManager.GetString("Sketch360", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sketch name.
        /// </summary>
        public static string SketchName {
            get {
                return ResourceManager.GetString("SketchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sketch Properties.
        /// </summary>
        public static string SketchProperties {
            get {
                return ResourceManager.GetString("SketchProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sketch properties....
        /// </summary>
        public static string SketchPropertiesMenuItem {
            get {
                return ResourceManager.GetString("SketchPropertiesMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 360 Sketch Saved.
        /// </summary>
        public static string SketchSaved {
            get {
                return ResourceManager.GetString("SketchSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sketch saved to downloads folder:
        ///{0}.
        /// </summary>
        public static string SketchSavedMessageFormat {
            get {
                return ResourceManager.GetString("SketchSavedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string VersionFormat {
            get {
                return ResourceManager.GetString("VersionFormat", resourceCulture);
            }
        }
    }
}
